services:
  - type: web
    name: feedback-platform-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn feedback_project.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
